/* To see the assembly code generated by the C compiler, we can use the “-S” option on the command line: gcc -O -S programa.c -masm=intel*/
/* If we use the ’-c’ command line option, GCC will both compile and assemble the code: gcc -O2 -c code.c*/
/* To inspect the contents of object code files,: objdump -d code.o*/

/* gcc -Wall -o C001 C001.c */
 
// file : Leaf.c

# include <stdio.h>

/* intLeaf (int g, int h, int i, int j)
	{
		int f;
		f = (g + h) –(i+ j);
		return f;
	}
*/	

//Parameter variables g, h, i,and j in argument registers rcx, rdx, r8, and r9

extern int leaf(int g, int h, int i, int j);         // prototipo funcion

int main()
{
int g = 10, h = 20, i = 30, j = 40;

	int f = leaf(g, h, i, j);   // llamada a la funcion
    printf("f = %d\n", f);
    return 0;
}


