/* To see the assembly code generated by the C compiler, we can use the “-S” option on the command line: gcc -O -S programa.c -masm=intel*/
/* If we use the ’-c’ command line option, GCC will both compile and assemble the code: gcc -O2 -c code.c*/
/* To inspect the contents of object code files,: objdump -d code.o*/

/* gcc -Wall -o C001 C001.c */
 
// file : add.c

# include <stdio.h>

/* intLeaf
	(int g, int h, int i, int j)
	{
		intf;
		f = (g + h) –(i+ j);
		return f;
	}
*/	
//Parameter variables g, h, i,and j in argument registers rcx, rdx, r8, and r9

int leaf(int g, int h, int i, int j);         // function prototype

int main()
{
int g = 10;
int h = 20;
int i = 30;
int j = 40;

	int f = leaf(g, h, i, j);   // function call
	
    printf("f = %d", f);
	
    return 0;
}

int leaf(int g, int h, int i, int j)     // function definition   
{	
	int f;
		f = (g + h) - (i+ j);
		return f;	// return statement         
}

