/* To see the assembly code generated by the C compiler, we can use the “-S” option on the command line: gcc -O -S programa.c -masm=intel*/
/* If we use the ’-c’ command line option, GCC will both compile and assemble the code: gcc -O2 -c code.c*/
/* To inspect the contents of object code files,: objdump -d code.o*/

/* gcc  -o HelloCC HelloCC.c */
 
// file : HelloCC.c

# include <stdio.h>

float  a =  30.25;		//simple presición
float  a = -30.25;		//simple presición
double b =  30.25;		//doble presición
double b = -30.25;		//doble presición

int main ()
{
	
	float  c = 30.25;		//simple presición
	double d = 30.25;		//doble presición

return 0;
}

