/* To see the assembly code generated by the C compiler, we can use the “-S” option on the command line: gcc -O -S programa.c -masm=intel*/
/* If we use the ’-c’ command line option, GCC will both compile and assemble the code: gcc -O2 -c code.c*/
/* To inspect the contents of object code files,: objdump -d code.o*/

/* gcc  -o HelloCC HelloCC.c */
 
// file : stack-overflow.c

# include <stdio.h>
# include <string.h>


char cadena[50];

int main ()
{
    int len;
    printf("ingresar cadena: ");
	scanf("%s", &cadena);
	
    len = strlen(cadena) ;
 
    printf ("longitud cadena ingresada: = %d \n" , len ) ;
    return 0;
}
	
	
