/* To see the assembly code generated by the C compiler, we can use the “-S” option on the command line: gcc -O -S programa.c -masm=intel*/
/* If we use the ’-c’ command line option, GCC will both compile and assemble the code: gcc -O2 -c code.c*/
/* To inspect the contents of object code files,: objdump -d code.o*/

/* gcc -Wall -o C001 C001.c */
 
// file : add.c

# include <stdio.h>


int a = 0x12345678;			//variable global/estatica 

int mascara(int a);         // function prototype

int main()
{
    int x;  
    x = mascara(a);        // function call
    printf("sum = %X", x);
    return 0;
}

int mascara(int a)         // function definition   
{
    return  a & 0XFFFF0000;// return statement
}
